apertium/phenny

modules/pester.py, phenny
Added a pester plugin to 'pester' pester people to complete tasks. It currently implements the following functions -
(name-of-bot): pester (user) to (do something) # to start pestering someone
.pesters dismiss (name-of-pesterer) # dismiss pester
.pesters stop (person-you-are-pestering) # stop pestering
.pesters admin stop (pesterer) to (pesteree) # admin can stop any pester
Also, 2 new config file parameters have been added -
minutes_to_pester (minutes between 2 pesters, default set to 60 (1 hr))
pester_after_dismiss (minutes to wait before pestering after the pester has been dismissed, defaults to 300 (5 hrs))
=> Add pester plugin

modules/pester.py
The pester module now works with the following commands --
(name-of-bot): pester (user) (to do something) # to start pestering someone
.pesters dismiss (name-of-pesterer) # dismiss pester
.pesters stop (person-you-are-pestering) # stop pestering
.pesters admin stop (pesterer) to (pesteree) # admin can stop any pester
..and config-file parameters --
minutes_to_pester (minutes between 2 pesters, default set to 60 (1 hr))
pester_after_dismiss (minutes to wait before pestering after the pester has been dismissed, defaults to 300 (5 hrs))
=> Fixed pester module

modules/git.py, modules/svnpoller.py
The default.py file already has these two lines:
```
svn_repositories = {'svnRepoA':'https://svn.code.sf.net/p/...', 'svnRepoB':'https://svn.code.sf.net/p/...'}
git_repositories = {'gitRepoA':'https://api.github.com/repos/...'}
```
These lines need to be added:
```
svn_channels = {'svnRepoA': ['#this_channel', '#that_channel'], 'svnRepoB': ['#the_other_channel']}
git_channels = {}
```
As the comment mentions, if the name of a repository is present as a key in the `svn_channels` or `git_channels` dictionary, then messages for that repository will only be sent to the list of channels specified. Otherwise, messages will be sent to all channels.
=> Make repository monitoring channel-specific

modules/more.py
The `more` module uses up 2 messages when there is more than a single message in the list. It says the first message in the list, then prints out a notice to use `.more` in order to display the rest of the messages. However, when there are 2 messages in the list, the `more` module does not print out the 2nd message in the list directly. This commit changes that.
=> Make `more` module more efficient in its use of messages.

modules/git.py, modules/svnpoller.py
If the `git_channels` or `svn_channels` dictionary is not present, then phenny defaults to messaging all channels.
=> Check if channels dictionary is present

modules/clock.py, modules/eleda.py
Fixed GMT bug, where begiak would display an incorrect time (somewhat randomly, varying by launch), when asked `.time GMT`. Problem occurred because `.time` has an "autocomplete" for dates, but does not check if the timezone the user asked for is in the DB verbatim. Since the DB had tz's like GMT+1, it autocompleted to those, rather than using GMT. Fixed by checking for verbatim matches before "autocompleting" (This behavior already existed in `.tz`, not sure why it wasn't here). Additionally, fixed some possible confusion from autocomplete, by displaying the autocompleted city in the response. Example:
` <vigneshv>: .time San F`
` <begiak>: vigneshv: Thu, 31 Dec 2015 14:38:57 SAN FRANCISCO, CA`
=> Fixed GMT bug

modules/git.py
I've set up Jenkins to build the core Apertium tools and run regression tests. It's already sending webhooks so all that's needed for it to send build failure notifications is for you to merge this.
=> Handle webhooks from Jenkins

modules/git.py
Trim comments on commits, issues, and pull-requests so that phenny's final message is not long enough to be broken. Also trim commit queries but not commit messages.
Should fix #132.
=> GitHub comment trimming

modules/apy.py, modules/test/test_apy.py
Add unit tests for the APy module. As the tests test the functionality of the proposed APy module changes in #211, the branch for this PR is branched off the branch with those changes (and if merged, should be merged after that PR). The internals of `mock` and `urllib.error.HTTPError` cause a couple of exceptions to be thrown when the test is run, _which are ignored_ by `nosetests` by default.
=> Tests for the APy module

modules/head.py
Anchored links are links with a `#` part like `http://abc.com/def.html#gohere`. Also include a small regex fix.
=> phenny gives titles for anchored links

modules/iso639.py
Implemented this in response to https://github.com/goavki/phenny/issues/186. So, if the two-letter code is supplied, a three-letter code is given, and if a three-letter code is supplied, a two-letter code is given.
Also replaced old `%` format syntax with `.format()` syntax
=> Added reverse lookup for ISO639 codes, from two-letter to three-letter codes, and vice versa

bot.py, modules/git.py, modules/reload.py
As the newer and recommended `importlib` library is used instead of `imp`, `git.py` can be reloaded while leaving the server running. Some code has been refactored in `git.py`; while the server does not start automatically on start-up, this was the case before the changes too.
=> Fix the git reloading issue.

modules/git.py
phenny tests for a previous server in the setup() method, so the check is required in only one place and can be used by other functions such as the automatic server start.
=> Start gitserver automatically on start-up.

modules/git.py
Attempt to fix #251 with custom commit message reporting format, not using [`generate_report`](https://github.com/goavki/phenny/blob/master/tools.py#L40) from `tools.py`. This is only for webhook notifications; other commands like 'recent' will eventually also have to be changed but this fixes the current issue.
=> Truncate git commit messsages

modules/clock.py
We forgot to do so back in 5960c4ba14d6221344a10b108d7e66e7ebd05afa.
@jonorthwash FYI.
=> Update error message

bot.py
@jonorthwash It took a couple of hours to debug it, but finally I came to the conclusion what happened here and why it wasn't working.
As I suspected before, the problem was in #330. First error was caused because pong function wasn't called, so Begiak had to be disconnected (as it is in RFC 2812 Client Protocol - https://tools.ietf.org/html/rfc2812). I couldn't recreate the issue locally, because my config file had not `refreash_delay` set. So, the pong function wasn't called because one of the changes in #330 was overwriting the data, so the pong function, even though it was added before, was overwritten by new function (startup). I changed it to detect if module name already exists. Second error was showing after reconnecting, and it was caused because of ports being reused as Begiak …
=> Fixed pong

modules/test/test_apy.py
Before, Travis had this in every build:
```
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f51ec6f66d8>>
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/tempfile.py", line 450, in __del__
self.close()
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/tempfile.py", line 443, in close
self.file.close()
AttributeError: 'str' object has no attribute 'close'
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f51ec6e3390>>
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/tempfile.py", line 450, in __del__
self.close()
File …
```
=> Fix AttributeError in apy test

__init__.py, bot.py, default.py.example, irc.py, modules/sasl.py
Added new module called sasl.py, to authorize identity using SASL. You should register Begiak on NickServ first (if not done before). Also, there are few changes in config file, so if you run on already existing instance of Begiak, this changes should be made to default.py:
- Add "sasl = False(or True)" line.
- Uncomment "password = 'example'" line, and enter password to NickServ.
- Remove empty string in "ignore = ['']", line. So it would be "ignore = []" now.
=> SASL Authentication added

modules/git.py
Fixes #329
* `data['commits']` might fail if the attribute doesn't exist
* We want to log events without this attribute as well
* Gives us the commits (if given) for easier debugging
* Sometimes we actually don't want to print something
@jonorthwash /cc
=> Refactor "no messages" warning

.travis.yml
* (success -> failure) -> notification
* (failure -> failure) -> no notification
It's annoying when a restarted broken build generates additional notifications.
=> Only notify on newly broken builds

modules/admin.py, ssh/gen-key.sh, ssh/sign-msg.sh, ssh/verify-msg.sh
Fixes #392
```
$ ls ssh
gen-key.sh  sign-msg.sh  verify-msg.sh
```
Setup:
```
$ ./ssh/gen-key.sh 
```
**Note:** begiak needs a copy of the `~/.phenny/id_rsa.pub` file generated.
Signing a command:
```
$ ./ssh/sign-msg.sh .upgrade e76f655a5a62fafe91792e139eaceb6c75659a0e
.upgrade e76f655a5a62fafe91792e139eaceb6c75659a0e RCb7xQFrHrUfVtx+MWnTplrpoq01pa0mVuVsrT1SYxEk6AvNkiTa0O+noAQd8zVYMgvgvwJJWeSa5IFuxbPx93JzTvcEPo2ApC71R+svWKbOkgn8dcWlTdXE0WLo9Q71XZ0h6MeAfTMkK0FdlRAXqt4atPo6RPgcoHVGG7k3gb0=
```
=> Enable authoritative commands

modules/test/test_weather.py, modules/weather.py
Fixes #305 
`display_name` is unused anyway.
Testing `latitude` and `longitude` instead.
=> [weather.py] Drop display_name and test coordinates

modules/git.py, phenny
See https://github.com/apertium/phenny/pull/422#issuecomment-408887463 for reference.
`apertium/bootstrap` was renamed to `apertium/apertium-init`, right?
```
git_channels = {
'apertium/*': ['#apertium'],
'hfst/hfst': ['#hfst'],
'jonorthwash/ud-annotatrix': ['#_u-dep'],
}
```
Optionally, change `hfst/hfst` to `hfst/*` or maybe `hfst/hfst-*`.
=> [git.py] git_channels: event -> repo

modules/greeting.py, modules/test/test_greeting.py, phenny
Fixes #427 
Trying to fully keep track of joined users for deciding when to (not) greet depending on their presence in the channel.
It's untested as my Phenny bot lacks the database stuff that begiak uses in this module.
I don't know if this is the proper way to make a PR, as I'm still unfamiliar with Git and GitHub. Sorry in advance.
=> Greet people after N seconds

__init__.py, modules/__init__.py, modules/test/test_coverage.py, unit-tests.sh
The `NOSE_COVER_INCLUSIVE` flag seems to misbehave, so I had to work around it.
```
Name                            Stmts   Miss  Cover
---------------------------------------------------
phenny/__init__.py                 63     41    35%
__init__/__init__.py               63     41    35%
bot.py                            213    164    23%
irc.py                            200     76    62%
metar.py                          175     66    62%
phenny/modules/__init__.py          6      1    83%
modules/__init__.py                 6      1    83%
modules/admin.py                   89     58    35%
modules/apertium_wiki.py           37      5    86%
modules/apertium_wikistats.py      79     59    25%
modules/apertiumchill.py           55     41    25%
modules/apy.py                    240 …
```
=> Include all modules in coverage report

modules/apertium_wiki.py, modules/test/test_apertium_wiki.py
Fixes #474
Remove the excess .log added to the end of the URL when .logs is
used with no arguments.
=> Fix the URL generated when no arguments is passed to .logs

apertium_wikistats_bot.py
This attempts to fix #485.
I created a helper function `formatNumberThousands()`  formats the numbers with the thousands separator.
This is used in the `getStats()` function to format the numbers with the `,`.
=> Add missing commas - Attempts to fix #485

modules/test/test_weather.py
According to [this page](https://en.wikipedia.org/wiki/Decimal_degrees) about _Decimal Degrees_ on _Wikipedia_, `0.01 decimal degress` corresponds to approximately `1.11 km`.
Using  `0.07` for `delta`, would correctly assert coordinates which are `7.77km` away from the "true coordinates".
In my opinion, this seems reasonable to assert if the coordinates are inside a city.
I have changed the `assertAlmostEqual` function parameters to use a `delta` of 0.07 instead of a number of decimal places.
=> Update weather module tests - fix #514

modules/clock.py
Certain sections of the wikipedia page for timezones do not have a link for the time zone (for example, the first two rows displayed in the image below).
After consulting the guide for HTML scraping at http://effbot.org/zone/element-index.htm#documentation, I added a failsafe for the cases in which there is no link. Since the footnotes are made using `<sub>`, and the `.text` function returns the string before any sub-elements, this should fix the issue mentioned above.
Make sure to test if this works.
=> Fix for issue #491

modules/info.py
`command` is a string and `func` was previously undefined.
=> typo in info.py

modules/ethnologue.py, modules/iso639.py, modules/test/test_iso639.py
I was messing around the Ethnologue scraping code in the hope of fixing the broken tests. I didn't manage that, but I did find a tab-separated text file containing the data that the `ethnologue` and `iso639` modules scrape. Anyway, this replaces scraping 26 Ethnologue pages and 3 Wikipedia pages with parsing a single text file, which seemed like an improvement.
=> scrape ISO 639 codes from single source
