modules/git.py

This is part of a GCI task, [http://www.google-melange.com/gci/task/view/google/gci2014/5226079329452032](Document phenny/begiak git plugin), and this fork contains changes to modules/git.py that:
* document the code (docstrings and comments)
* perform basic cleanup

Document modules/git.py and perform a little cleanup

---

modules/mailing_list.py
phenny

[GCI '14](http://www.google-melange.com/gci/task/view/google/gci2014/5312553932554240)
Jonathan, I created a gmail account to receive the messages, let me know how I can get the credentials to you.

Mailing list reporter

---

modules/mailing_list.py

obfuscate the emails
fail gracefully when it's not configured correctly
added function to get last message in a list
allowing many channels to broadcast to
[for GCI 14](http://www.google-melange.com/gci/task/view/google/gci2014/5312553932554240)

mailing list fixes

---

modules/mailing_list.py

[I've also updated the wiki](http://wiki.apertium.org/wiki/Begiak#Apertium_features)

mailinglist: moar obfuscation, easier interface

---

modules/git.py

Make begiak's git module support more GitHub events

Add more GitHub events

---

modules/git.py

Fix bug where messages went to a non-existent list

Git module bug-fix

---

modules/git.py

Lots of small fixes to modules.git.py. Tested on a local phenny set-up.

Make GitHub events work

---

modules/git.py

Fix formatting for GitHub events as per firespeaker's comment on task description page.

Fix formatting for GitHub events

---

modules/pester.py

Added a 'pester' module which allows a user to pester another to complete a given task.

Add pester plugin

---

modules/git.py

Fix more formatting (see PR #108)

Fix formatting for GitHub messages

---

modules/git.py

Add more detail to issue messages (assigned to whom or labeled with what) and add URLs for pull requests, issues, commits, etc.

Add detail to messages

---

modules/pester.py

Please DO NOT revert my previous pull request (#115). Merge this PR into the existing repo (with PR #115)
Commands --
(name-of-bot): pester (user) to (do something) # to start pestering someone
.pesters dismiss (name-of-pesterer) # dismiss pester
.pesters stop (person-you-are-pestering) # stop pestering
.pesters admin stop (pesterer) to (pesteree) # admin can stop any pester

Pester plugin now works.

---

modules/pester.py

Changed command names --
.pesters dismiss -> .pesters snooze
.pesters stop -> .pesters dismiss

Changed command names.

---

modules/pester.py

The pester module now displays the creation time of the pester while pestering.

Changed pester message.

---

modules/tell.py

Makes begiak explain how you can read messages people have left you instead of just "you have messages".

explanation on how to read messages

---

modules/weirdfun.py

currently running only .hug gives an attribute error. This fixes that.

prevent .hug error

---

modules/apertium_wiki.py
modules/wikipedia.py
modules/wiktionary.py

As asked in this task: https://codein.withgoogle.com/dashboard/task-instances/5367746678226944/

Add point command to (a)wiki plugins

---

modules/clock.py

Added capability to do timezone arithmetic in the clock module.

Add Timezone Math

---

modules/git.py
modules/svnpoller.py

The modules git.py and svnpoller.py now print out a URL along with other information with the 'info' and 'recent' commands.

Added URL functionality to git.py and svnpoller.py

---

modules/clock.py
modules/fs_quotes.py
modules/search.py
modules/urbandict.py

FIxing issue #150 
Would be great if I could get task credit for this for GCI. But I am submitting this anyway.

Added point commands to .g, .urb, .time, .randquote

---

modules/eleda.py
tools.py

Phenny now sends private messages containing translations whenever nicks are being followed. Translations for each nick are requested only once, though many nicks may receive PMs.

Make phenny privately message translations (the .follow command)

---

modules/eleda.py
modules/iso639.py

Reverse follow (en-es) works.

---

modules/apertium_wiki.py

Add .log(s) and fix indentation in apertium_wiki.py

---

modules/apertium_translate.py

Also PEP8-ed the file
Currently it uses Turkic APY since that is the only instance that can analyse and generate. So it is limited to the Turkic language list.

Add analysis and generation mode commands

---

modules/sfissues.py
requirements.txt

Configuration is as follows:
```
sf_issues = {
'apertium': ("https://sourceforge.net/p/apertium/tickets/feed.rss", ["#apertium"]),
}
```

Add quick and dirty sf issues module

---

modules/apertium_translate.py
modules/fs_quotes.py
modules/queue.py

This fixes some import errors I got at start up when coding the other PR.

Fix import errors

---

modules/posted.py
requirements.txt

This should fix [this issue](https://github.com/goavki/phenny/issues/192) with the `posted.py` module.

Use 'humanize' module instead of 'ago'

---

modules/apy.py

Fix broken stats and calccoverage functions. Add perword function. Minor formatting fixes.

Improve APy module

---

LICENSE

Add EFLv2 license

---

modules/apertium_wiki.py
modules/head.py
modules/posted.py
modules/wikipedia.py

Links posted for Wikipedia, Wiktionary, and Apertium wiki are recorded by posted.py.

Make posted module record Wiki links

---

modules/git.py

Commit comment edit/delete events aren't supported by the API ([reference](https://developer.github.com/v3/activity/events/types/#commitcommentevent)). Should fix #223.

Report edited and deleted comments on issues and PRs

---

modules/apy.py
modules/mylife.py
modules/search.py
modules/test/test_mylife.py
modules/test/test_search.py
modules/test/test_vtluugwiki.py

Includes some small modifications to the search.py and apy.py modules.

Fix tests again

---

modules/__init__.py
modules/away.py
modules/eleda.py
modules/greeting.py
modules/lastfm.py
modules/logger.py
modules/more.py
modules/pester.py
modules/queue.py
modules/seen.py
modules/tell.py

This is a solution for issue #158. The bot now ignores case when comparing nicks. However, the bot still differentiates between capitalized and lowercase versions of the bot's nick.

Bot less strict with nick capitalization

---

modules/git.py

Revert "Start gitserver automatically on start-up."

---

modules/git.py
modules/reload.py

The previous PRs were reverted because they caused more errors than they fixed. This PR presents a cleaner solution to the new and the old issues: the gitserver starts automatically with phenny, and is safely turned off when the git module is reloaded, but not started again. No other errors [should] occur.
Added functionality to `reload.py`: if a module has a `teardown()` function, it is called before the module is reloaded.

Try to fix issues caused by #242 and #243.

---

modules/test/test_wiktionary.py
modules/wiktionary.py

New behavior:
```
< shardulc> .w Joke
< phenny> Perhaps you meant 'joke'?
< phenny> joke — noun: 1. An amusing story, 2. Something said or done for amusement, not in seriousness, 3. figuratively: The root cause or main issue, especially an unexpected one
```

Attempt to fix #238 and #239, and add unit test accordingly.

---

modules/wikipedia.py

Attempt to fix #255

---

irc.py
modules/tell.py
modules/test/test_tell.py

Send message only once per nick

---

modules/git.py
modules/more.py

Use 'more' module in git webhook

---

modules/git.py

Close server socket properly and on quit/crash

---

bot.py
modules/apertium_wikistats.py
modules/apy.py
modules/calc.py
modules/clock.py
modules/foodforus.py
modules/greeting.py
modules/pester.py
modules/seen.py
modules/sfissues.py
modules/slogan.py
modules/startup.py
modules/tell.py
modules/test/test_away.py
modules/test/test_calc.py
modules/urbandict.py
modules/weather.py
tools.py

Clean up whitespace-only lines

---

modules/git.py

@shardulc #210 became redundant in #276.

Remove unnecessary truncating

---

.gitignore

Ignore *.db files

---

modules/apertium_wikistats.py

Hi! I'm adding autocoverage support for begiak, now with command ".awikstats coverage [here 3 letter language code]" you can run coverage and it will automatically update the wiki stats page after coverage is completed. There aren't many changes here, most changes are in scripts on SVN.

Added autocoverage support

---

modules/clock.py

Fix clock module wiki scraping

---

modules/mailing_list.py

Fix list_report third argument

---

modules/git.py
modules/greeting.py
modules/test/test_greeting.py

Only greet on round binary join count

---

irc.py
modules/apy.py
modules/fs_quotes.py
modules/git.py
modules/more.py
modules/queue.py
modules/svnpoller.py
modules/test/test_apy.py
modules/test/test_more.py
tools.py

Fix add_messages break_up logic

---

bot.py
modules/git.py

Revert "Remove unnecessary truncating"

---

modules/mailing_list.py

Fixes #260
@wei2912 Friendly ping.

Fix unicode processing

---

modules/mailing_list.py
modules/test/test_weather.py

Towards #159
See https://github.com/goavki/phenny/issues/259#issuecomment-354063287 for reference

Implement .more for check_mail

---

modules/calc.py
modules/git.py
modules/test/test_calc.py
requirements.txt

Fixes #278 
Features:
- Support for operators such as +, -, *, /, ** (power, or ^)
- Logarithms
- Trigonometry, Polynomials
- Trigonometric, hyperbolic, exponential, roots, logarithms, absolute value, spherical harmonics, factorials and gamma functions, zeta functions, polynomials, special functions etc (more here - http://www.sympy.org/en/features.html)
- Arbitrary precision integers, rationals, and floats
- Finding unknown variables
Now, you can also use expressions without multiplication sign so e.g '3x' instead of '3 * x' or '2(x-1)' instead of '2 * (x-1)' etc.
Some simple examples of use:
.c 3+2
.c 2+x=4
.c 2^x=4
.c sin(90)
etc

Replacement for calc module with SymPy

---

modules/git.py
modules/svnpoller.py
tools.py

Fix truncate bugs

---

irc.py
modules/apertium_wiki.py
modules/svnpoller.py
modules/wikipedia.py
tools.py

Encapsulate magic number 430

---

modules/git.py

Hide commits to branches/forks

---

__init__.py
bot.py
irc.py
modules/botsnack.py
modules/clock.py
modules/ethnologue.py
modules/git.py
modules/iso639.py
modules/mailing_list.py
modules/seen.py
modules/startup.py
phenny
tools.py

Overhaul logging

---

modules/git.py
modules/more.py
modules/posted.py
modules/test/test_more.py
tools.py

Save .more messages to a database

---

modules/apertium_wiki.py

`TypeError: Can't convert 'bytes' object to str implicitly (file "/home/begiak/phenny/modules/apertium_wiki.py", line 86, in apertium_wiki)`
Seems like I messed up on the last change to this code.

Fix TypeError

---

bot.py
modules/reload.py

Refactor bot.py logging

---

modules/git.py

Produce a slightly more helpful error message

---

bot.py
modules/reload.py
modules/startup.py

Forgot some `startup.py` code in #314.

[v2] Refactor bot.py logging

---

modules/git.py
tools.py

Ensure port reuse won't fail

---

modules/git.py

Wait for socket to shutdown on unexpected exit

---

modules/apertium_wikistats.py

As @jonorthwash requested, coverage will now be sent on private message.

 .awikstats coverage to private message

---

modules/search.py

Fixes #354 and #356 :)
HTML tags are now removed (before and after fix):

Improved search module

---

__init__.py
modules/git.py

Hopefully fixes #334 
See https://github.com/goavki/phenny/issues/334#issuecomment-355751956 for reference
@jonorthwash /cc

Resolve issues with git.py

---

modules/more.py

Split .more output if necessary

---

modules/clock.py
modules/remind.py
modules/test/test_clock.py
tools.py

Fixes #322 
Incidentally disentangles and simplifies the code.
@shardulc FYI

Refactor clock.py

---

modules/test/test_iso639.py

As in #345 
I will add more later.

Added is_up to test_iso639.py

---

modules/test/test_slogan.py

Skip tests on server SSL error

---

modules/search.py
modules/test/test_search.py

As described in #340 
New .suggest uses Google's Suggestions API, and sends 10 results through more module :)

Replacement for .suggest

---

modules/apy.py
modules/fs_quotes.py
modules/git.py
modules/mailing_list.py
modules/more.py
modules/queue.py
modules/search.py
modules/test/test_apy.py
modules/test/test_more.py
tools.py

Fixes #292
@wei2912 /cc
@shardulc /cc

Have .more messages be tagged

---

modules/queue.py

@shardulc /cc
Sorry, missed one.

Fix argument order

---

modules/apertium_wikistats.py
modules/clock.py
modules/ethnologue.py
modules/iso639.py
modules/queue.py
modules/remind.py
modules/seen.py
modules/test/test_clock.py
modules/test/test_greeting.py
modules/test/test_iso639.py
modules/test/test_more.py
modules/test/test_remind.py
modules/test/test_tell.py
phenny
tools.py

Fixes #319 
* `setup` methods are used consistently
* `db_path` guarantees the existence of the `.phenny` directory
* `read_db` and `write_db` take care of paths and encoding

Refactor databases and make them work on Travis

---

modules/clock.py

Towards #360
@gstark0 /cc
@sushain97 /cc

Limit .time output to three matches

---

modules/queue.py
phenny
tools.py

Fix dot path

---

modules/clock.py
modules/test/test_clock.py

Fixes #360 
@gstark0 /cc
@sushain97 /cc

Drop scraped +/-X entries

---

web.py

Set socket default timeout

---

modules/more.py

Port messageAlert to more.py

---

default.py.example
modules/git.py
phenny

Fixes #384
@jonorthwash /cc
**Note:** `begiak` needs `githook_autostart = True` set.

Change githook startup behavior

---

modules/apertium_wikistats.py

Improve awikstats informational message

---

.travis.yml
clean-cache.sh
modules/clock.py
modules/ethnologue.py
modules/iso639.py
modules/test/test_iso639.py
tools.py
web.py

Cache scraped data

---

modules/git.py
phenny

Refactor git hook orchestration

---

README.md
__init__.py
irc.py
modules/imdb.py
modules/linx.py
modules/mylife.py
modules/test/test_imdb.py
modules/weather.py
modules/wuvt.py
phenny

* Python version required: `3.2` -> `3.4`
* Add support for TLS client certs
* Fix imdb and mylife
* Refactor linx.py
* Refactor weather.py location()
* wuvt: don't blow up if listeners is None

Merge changes from upstream

---

.travis.yml
test/test_irc.py
wiki.py

Bring back Python 3.4 tests

---

modules/queue.py
modules/test/test_queue.py
tools.py

Refactor queue module

---

modules/iso639.py

Fixes #421 
Follow-up on fa0858a792d4739a2232a308b40331effdfecb36

Fix .wikitable scraping

---

bot.py
irc.py

Report errors to admins (only)

---

bot.py
irc.py
modules/apertium_wiki.py
modules/clock.py
modules/fs_quotes.py
modules/test/test_clock.py
modules/urbandict.py
modules/wikipedia.py
modules/wiktionary.py

Generate point commands

---

bot.py
irc.py
modules/apertium_wiki.py
modules/clock.py
modules/fs_quotes.py
modules/test/test_apertium_wiki.py
modules/test/test_wikipedia.py
modules/urbandict.py
modules/wikipedia.py
modules/wiktionary.py
test/test_bot.py
test/test_irc.py

Pass command args properly

---

modules/clock.py
modules/ethnologue.py
modules/iso639.py
modules/test/test_wuvt.py
web.py

When the scraping code changes, invalidate the html cache.
See #431

Safe automatic rescraping

---

modules/greeting.py
modules/test/test_greeting.py

[greeting.py] Tell people about NickServ

---

modules/gci.py

Add gci.py module

---

modules/gci.py

Improves on https://github.com/apertium/phenny/issues/437.

Make several enhancements to the GCI module

---

modules/apertium_wiki.py
modules/test/test_apertium_wiki.py

#435 
I added the requested features as well as a few of my own. Tested it in a personal IRC channel, and I can run it for people if they want. 
Also changed the endpoint for log to the apertium folder in order to not reveal all the non-apertium related stuff in the apache server.

Revamped logs command

---

modules/git.py

see [this issue](https://github.com/apertium/phenny/issues/434)

flood control

---

modules/issue.py
modules/test/test_issue.py
web.py

for:
- https://codein.withgoogle.com/dashboard/task-instances/5046772335378432/
based on:
- https://github.com/apertium/phenny/issues/433

add issue.py - create a new github issue

---

init.sh

This PR fixes the init script and closes https://github.com/apertium/phenny/issues/484.

Fix the init script

---

modules/mailing_list.py

Fix unicode in email subject

---

modules/apy.py

Attempts to fix #482, where warning messages due to incorrect usage are shown to administrators instead of the user.
Additionaly, on line 103 a try/except block appears to be redundant since the function never raises the exception trying to be caught.

Display error messages due to wrong usage to users instead of admins

---

modules/mailing_list.py

Re-added line which was accidentaly removed in fix #501.
Thank you @Androbin for pointing this out.

Readded line which was accidentaly removed in #501

---

modules/test/test_greeting.py

Fix a test

---

modules/alias.py
modules/tell.py

This removes alias code from tell into its own module

Add alias module

---

modules/alias.py
modules/seen.py
modules/tell.py
modules/whois.py

Add whois module

---

modules/apy.py

Add web translation

---

modules/language.py

This module scrapes language population and region data from Wikidata since it is no longer possible to get this from Ethnologue (#513).

create wikidata language module

---

modules/test/test_apertium_wiki.py

reference #478 
**Changes made** : 
- replaced double quotes for strings with single quotes.

replaced double quote strings with single quotes
